src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ArticleRepository::class)
 */
class Article
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text", length=100)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $body;

    public function getID(): ?int
    {
        return $this->id;
    }
    public function getTitle(): ?string
    {
        return $this->title;
    }
    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getBody(): ?string
    {
        return $this->body;
    }

    public function setBody(?string $body): self
    {
        $this->body = $body;

        return $this;
    }

}

src/Entity/Review.php
<?php

namespace App\Entity;

use App\Repository\ReviewRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ReviewRepository::class)
 * @ORM\Table(name="reviews")
 */
class Review
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer", name="review_id")
     */
    private $id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $rating;

    /**
     * @ORM\Column(type="datetime", name="created_at", nullable=true)
     */
    private $date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $summary;

    /**
     * @ORM\Column(type="text", name="review_body")
     */
    private $message_body;

    /**
     * @ORM\Column(type="boolean", name="is_reported", nullable=true, options={"default": false})
     */
    private $reported;

    /**
     * @ORM\Column(type="string", length=200, name="movie_title")
     */
    private $movieTitle;

    /**
     * @ORM\Column(type="string", length=150, nullable=true)
     */
    private $director;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $actors;

    /**
     * @ORM\Column(type="integer", name="release_year", nullable=true)
     */
    private $releaseYear;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $genre;

    /**
     * @ORM\ManyToOne(targetEntity=User::class)
     * @ORM\JoinColumn(name="user_id", referencedColumnName="user_id", nullable=true, onDelete="CASCADE")
     */
    private $user;

    /**
     * @ORM\Column(type="integer", name="view_count", options={"default": 0})
     */
    private $viewCount = 0;

    /**
     * @ORM\Column(type="datetime", name="updated_at", nullable=true)
     */
    private $updatedAt;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="movieID")
     */
    private $comments;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->date = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRating(): ?int
    {
        return $this->rating;
    }

    public function setRating(?int $rating): self
    {
        $this->rating = $rating;

        return $this;
    }

    public function getDate(): \DateTime
    {
        return $this->date;
    }

    public function setDate(\DateTimeImmutable $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getSummary(): ?string
    {
        return $this->summary;
    }

    public function setSummary(string $summary): self
    {
        $this->summary = $summary;

        return $this;
    }

    public function getMessageBody(): ?string
    {
        return $this->message_body;
    }

    public function setMessageBody($message_body): self
    {
        $this->message_body = $message_body;

        return $this;
    }

    public function getReported(): ?bool
    {
        return $this->reported;
    }

    public function setReported(?bool $reported): self
    {
        $this->reported = $reported;

        return $this;
    }

    public function getMovieTitle(): ?string
    {
        return $this->movieTitle;
    }

    public function setMovieTitle(string $movieTitle): self
    {
        $this->movieTitle = $movieTitle;

        return $this;
    }

    public function getDirector(): ?string
    {
        return $this->director;
    }

    public function setDirector(?string $director): self
    {
        $this->director = $director;

        return $this;
    }

    public function getActors(): ?string
    {
        return $this->actors;
    }

    public function setActors(?string $actors): self
    {
        $this->actors = $actors;

        return $this;
    }

    public function getReleaseYear(): ?int
    {
        return $this->releaseYear;
    }

    public function setReleaseYear(?int $releaseYear): self
    {
        $this->releaseYear = $releaseYear;

        return $this;
    }

    public function getGenre(): ?string
    {
        return $this->genre;
    }

    public function setGenre(?string $genre): self
    {
        $this->genre = $genre;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getViewCount(): int
    {
        return (int) $this->viewCount;
    }

    public function setViewCount(int $viewCount): self
    {
        $this->viewCount = $viewCount;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setMovieID($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getMovieID() === $this) {
                $comment->setMovieID(null);
            }
        }

        return $this;
    }
}

src/Controller/ArticleController.php
<?php
namespace App\Controller;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class ArticleController extends AbstractController {
    /**
     * @Route("/") 
     * @Method({"GET"})
     */ #instead of using routes.yaml and specificying the route there, we can do this
    public function index() {
        // return new Response('<h1>Hello<h1>');
        return $this->render('articles/index.html.twig');
    }

}

templates/articles/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Articles{% endblock %}



{% block body %}

{#    <form method="POST" action="{{ path('upload_test') }}" enctype="multipart/form-data">#}
{#        <input type="file" name="image">#}

{#        <button type="submit" class="btn btn-primary ">Upload</button>#}
{#    </form>#}


    {{ form_start(form) }} {# This is a post request to the same URL, the same route that the get request comes from #}

{#    {{ form_widget(form) }} #}{# This is used to render a form text box #}
    {{ form_row(form.movie_title) }}
    {{ form_row(form.summary) }}
    {{ form_row(form.message_body) }}
    {{ form_row(form.rating) }}
    {{ form_row(form.director) }}
    {{ form_row(form.actors) }}
    {{ form_row(form.duration) }}
    {{ form_row(form.picture) }}
 
    {{ form_row(form.save) }}

    {{ form_end(form) }}

{% endblock %}

templates/articles/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}SymphArt Articles ({{ pagination.getTotalItemCount }}){% endblock %}

{% block body %}
    <form>
        <div class="input-group mb-3">
            <input type="text"
                   name="q"
                   class="form-control"
                   value="{{ app.request.query.get('query') }}"
                   placeholder="Search..."
            >
            <div class="input-group-append">
                <button type="submit"
                        class="btn btn-outline-secondary">
                    <span class="fa fa-search"></span>
                </button>
            </div>
        </div>
    </form>

    {% if pagination %}
            <div class="row card-group"  id="articles">

    {% for article in pagination %}
                <div class="col-sm-12 col-md-4">
                    <div class="card border-r text-center border-primary">
                        <div class="card-body">
                            <h5 class="card-title">{{ article.movieTitle }}</h5>
                            <img class="card-img-top" src="{{ asset('images//films/')~article.picture}}" style="max-height: fit-content; max-width: fit-content; display: block"  alt="No image to display">
                            <p class="card-text">By {{ article.userID.firstName }}</p>
                            <a href="/article/{{ article.id }}" class="btn btn-primary border-r">Show</a>
                            <a href="/article/edit/{{ article.id }}" class="btn btn-secondary border-r">Edit</a>
                            {% if is_granted('ROLE_ADMIN') %}
                            <a href="#" class="btn btn-danger delete-article border-r" data-id="{{ article.id }}">Delete</a>
                            {% endif %}
                            <p class="card-text mt-4"><small class="text-muted">{{ article.NonRemovedComments|length}} comments</small></p>
                            <p class="card-text mt-4"><small class="text-muted">Last updated at {{ article.date|date('H:i:s')}} ago</small></p>
                        </div>
                    </div>
                </div>
    {% endfor %}

            </div>






    {% else %}
        <p>Sorry you have not articles to display<p>
    {% endif %}


<div class="my-5">
    {{ knp_pagination_render(pagination) }}
</div>

{% endblock %}

{% block javascripts %}
    <script src="/js/main.js"></script>
{% endblock %}

templates/articles/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Articles{% endblock %}

{% block body %}
    <h1> Your review</h1>
{{ form_start(form) }} {# This is a post request to the same URL, the same route that the get request comes from #}
    {{ form_row(form.movie_title) }}
    {{ form_row(form.summary) }}
    {{ form_row(form.message_body) }}
    {{ form_row(form.rating) }}
    {{ form_row(form.director) }}
    {{ form_row(form.actors) }}
    {{ form_row(form.duration) }}
    {{ form_row(form.picture) }}


    {{ form_end(form) }}
{% endblock %}

templates/articles/show.html.twig
{% extends 'content_base.html.twig' %}

{% block title %}{{ article.movieTitle }}{% endblock %}

{% block content_body %}
    <div class="12">
        <div class="mt-2 row">
            <div class="col-sm-12 col-md-6">
                <img class="img-fluid mb-5"
                     src="{{ asset('images/films/')~article.picture }}">
            </div>
            <div class="col-sm-12 col-md-6">
                <h1>{{ article.movieTitle }}</h1>
                <small>By {{ article.userID.firstName }} {{ article.date|date('d:M:Y') }}</small>
                <p class="justify-text">My article: {{ article.messageBody }}</p>
                <p class="justify-text">I rated this {{ article.rating | default("NOT RATED") }}/10</p>
                <p class="justify-text">The director was {{ article.director | default("NO DIRECTOR SET") }}</p>
                <p class="justify-text">The actors were was {{ article.actors | default("NO ACTOR SET") }}</p>
                <p class="justify-text">The duration was {{ article.duration|date('H:i:s')}}</p>
            </div>
            <hr>

            {# Method allows for form to be sent and extracted. To extract data, name must be given for each field #}
            {# If you need to extract and reference the id number which is labeled like this, {} do it like below, where id: si what was specified in the controller url #}
            <div class="col-12">
                <h2 class="mt-5 mb-4">{{ article.NonRemovedComments|length }} comments</h2>
                {% if is_granted('ROLE_USER_COMMENT') %}

                <form method="POST" action="{{ path('article_submit_comment', {id: article.id}) }}">
                    <div class="input-group">
                        <textarea class="form-control" name="commentData" aria-label="With textarea"></textarea>
                        <div class="input-group-prepend">
                        <input type="hidden" name="currentUser" value="{{ app.user.firstName }}">
                            <button class="btn btn-outline-secondary" value="Submit" name="submitButton" type="submit">Submit</button>
                        </div>
                    </div>
                </form>

                    {% endif %}
                </div>
            {% for comment in article.NonRemovedComments %}
                <div class="row">
                    <div class="col-sm-12 col-md-2">
                        <img  class="profile-img-r img-fluid mb-5"
                              src="{{ asset('images//users/')~comment.userID.picture }}">
                    </div>
                    <div class="col-sm-12 col-md-10">
                        <h3>{{ comment.userID.firstName }}</h3>
                        <small> Sent at {{ comment.date|date('H:i:s') }}</small>
                        <p class="justify-text">{{ comment.commentBody }}</p>
                        {% if comment.isDeleted %}
                            <span class="fa fa-close"></span> deleted
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
            </div>
            <div class="col-12">
                <div class="row">
                    <a  href="/">Go Back</a>
                </div>
            </div>
        </div>

    </div>
{% endblock %}